### ISSUE TITLE
add support for widgets

### ISSUE THREAD

**Issue by formula-spectre** [iamrasel/lunar-launcher#11]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/iamrasel/lunar-launcher/issues) or [closed](https://github.com/iamrasel/lunar-launcher/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have already checked the [WIKI](https://github.com/iamrasel/lunar-launcher/wiki) pages and made sure that the feature isn't already exist.
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.

### Feature description

I would love to have widgets on my home screen, or even on a separate screen, like KISS does; in the main screen you can stack widgets, enlarge or shrink their height (maybe even side by side?)

### Additional information

something among the line of how kiss handles widgets

**Comment by iamrasel** [comment]
I already have this in my mind, maybe someday I will implement this feature too.

**Comment by formula-spectre** [comment]
cool! wish I could help but I know nothing about android dev..

**Comment by iamrasel** [comment]
You can help the development by making [donations](https://iamrasel.github.io/donate), that would encourage me to continue this project.
