### ISSUE TITLE
Favorite Apps do not show

### ISSUE THREAD

**Issue by calm3285** [iamrasel/lunar-launcher#127]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/iamrasel/lunar-launcher/issues) or [closed](https://github.com/iamrasel/lunar-launcher/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.

### App version

2.8.2

### Android version

13

### Steps to reproduce the bug

The favorite apps wont show up

### Expected behavior

To pop up

### Screenshots/Screen recordings

![Screenshot_20240320_211603_Lunar Launcher](https://github.com/iamrasel/lunar-launcher/assets/41839986/36d93600-6a9d-4c92-8c4b-a1613e4de331)

**Comment by fs-sifat** [comment]
Issue #114 
Make sure that there are no existing issues - open or closed
