### ISSUE TITLE
[Feature Request] Ability to hide apps.

### ISSUE THREAD

**Issue by Vermillion-oss** [iamrasel/lunar-launcher#128]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/iamrasel/lunar-launcher/issues) or [closed](https://github.com/iamrasel/lunar-launcher/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have already checked the [WIKI](https://github.com/iamrasel/lunar-launcher/wiki) pages and made sure that the feature isn't already exist.
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.

### Feature description

Quite simple, just a section in the settings screen to choose which apps you don't want to appear on the home screen.

**Comment by fs-sifat** [comment]
it'll be a useful feature, why did you close the this issue?

**Comment by Vermillion-oss** [comment]
> it'll be a useful feature, why did you close the this issue?

It was already mentioned in issue #6.
