### ISSUE TITLE
unable to uninstall from f droid

### ISSUE THREAD

**Issue by MaybeOnce** [iamrasel/lunar-launcher#13]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/iamrasel/lunar-launcher/issues) or [closed](https://github.com/iamrasel/lunar-launcher/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.

### App version

15.0

### Android version

android 9

### Steps to reproduce the bug

1
 From app listing in f Droid. Select Uninstall. Then ok
2.  Error message : failed to uninstall due to unknown error.

### Expected behavior

Application is uninstalled.

**Comment by iamrasel** [comment]
I have just reproduced your issue, and it seems like you hadn't disabled Device Admin permission for Lunar Launcher before trying to uninstall it. Always remember to disable Device Admin permission manually before trying to uninstall any android app, otherwise you won't be able to uninstall it.

**Comment by MaybeOnce** [comment]
Thank you.  Working as expected now.  Sorry, if I missed that in the documentation.

**Comment by iamrasel** [comment]
This info is not available in documentation. This is just a working procedure of android system.
