### ISSUE TITLE
App crash when trying to change volume

### ISSUE THREAD

**Issue by Vilianexe** [iamrasel/lunar-launcher#15]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/iamrasel/lunar-launcher/issues) or [closed](https://github.com/iamrasel/lunar-launcher/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.

### App version

17.4

### Android version

android 12

### Steps to reproduce the bug

1. Mute the cellphone sounds
2. Open the bottom tab
3. Try to change the call volume
4. The app crash

### Expected behavior

The volume to change without crash

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/72302817/192545254-adbad388-242d-48d9-85ee-8e58394640da.mp4

### Logs

I don't know how i can gather logs 

### Additional information

https://user-images.githubusercontent.com/72302817/192544240-13ef9ed4-ea61-4ca0-b935-b9767e547048.mp4

The crash only occur when the sound is muted(like in the video)

**Comment by iamrasel** [comment]
Notification and ringer volumes slider, both won't work while the device is in dnd or silent mode. These two slider should stay disabled while those modes are on.

Already took care of them for dnd mode, but didn't noticed about the silent mode before. Thank you for showing me this, it'll be fixed soon.

**Comment by iamrasel** [comment]
You can collect crash logs of your device using ADB.

**Comment by iamrasel** [comment]
Fixed
