### ISSUE TITLE
Hide notification bar while in launcher

### ISSUE THREAD

**Issue by Terkyz** [iamrasel/lunar-launcher#17]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/iamrasel/lunar-launcher/issues) or [closed](https://github.com/iamrasel/lunar-launcher/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have already checked the [WIKI](https://github.com/iamrasel/lunar-launcher/wiki) pages and made sure that the feature isn't already exist.
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.

### Feature description

Recently I was using Olauncher Clutter Free, which is an excellent launcher, and the same by default inside the launcher (in the list of applications, or the menu as such by pressing the Home button) has hidden the notification bar, and perhaps in Lunar Launcher this may make sense too, because in the main menu and have almost all the information that the search bar has, except the number of notifications, and another.

### Additional information

It may be an optional behavior, configurable in the launcher options.

**Comment by iamrasel** [comment]
As far as I could understand from what you said is - you want the ability to hide the status bar, right?

**Comment by Terkyz** [comment]
> As far as I could understand from what you said is - you want the ability to hide the status bar, right?

If it's possible, yeah
