### ISSUE TITLE
How do I set up OWM correctly?

### ISSUE THREAD

**Issue by Terkyz** [iamrasel/lunar-launcher#18]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/iamrasel/lunar-launcher/issues) or [closed](https://github.com/iamrasel/lunar-launcher/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have already checked the [WIKI](https://github.com/iamrasel/lunar-launcher/wiki) pages.
- [X] I have taken the time to fill in all the required details. I understand that the question will be dismissed otherwise.

### What is/are your question(s)?

How can I configure OpenWeatherMap(OWM) correctly? In "City name" I add the same that OWM shows and in OWM API Key I put the last numbers that shows the URL of that city, but even so and after restarting the launcher does not work, or in general does not show anything...

### Additional information

In KDE Plasma there is a plasmoid called Event Calendar that also works with OWM but when typing the name of the city, it automatically gives a list of cities with that name and gives the user the ability to choose which is his, maybe something like this could be implemented to facilitate this process.

**Comment by iamrasel** [comment]
In the `City Name` field, input the name of the city you live in, like `New York` or `London`. And the owm api key is a 32 digit word which is made of letters and numbers. You can get one for free from [here](https://openweathermap.org/api) (login required).
