### ISSUE TITLE
Add a color indicative of the place that has an app as favorite

### ISSUE THREAD

**Issue by Terkyz** [iamrasel/lunar-launcher#19]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/iamrasel/lunar-launcher/issues) or [closed](https://github.com/iamrasel/lunar-launcher/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have already checked the [WIKI](https://github.com/iamrasel/lunar-launcher/wiki) pages and made sure that the feature isn't already exist.
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.

### Feature description

If possible, add a color or an indication that an app already has that "favorite" space in [this](https://github.com/iamrasel/lunar-launcher/blob/main/fastlane/metadata/android/en-US/images/phoneScreenshots/3.png) section.

### Additional information

I know I can tell which app has to be spaced quickly using the quick menu itself but it could be a heck of a lot faster to have an indicator there, like the color of the app icon or its initial letters

**Comment by iamrasel** [comment]
It's a good idea, will try.
