### ISSUE TITLE
Worse performance in v2.0

### ISSUE THREAD

**Issue by Terkyz** [iamrasel/lunar-launcher#20]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/iamrasel/lunar-launcher/issues) or [closed](https://github.com/iamrasel/lunar-launcher/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.

### App version

v18.9.1 and v2.0

### Android version

Android 11

### Steps to reproduce the bug

1. When I open an application and close it, now the time it takes to return to the launcher is much longer, remaining in a blank space with my wallpaper while loading (probably in the video is not noticeable but it is much longer).

2. When using the text search and pressing the (x) the launcher takes longer to respond, previously it was an immediate response.

### Expected behavior

The launcher reacts immediately, without timeouts or waiting times...

### Screenshots/Screen recordings

https://imgur.com/a/DQ4IMOR

### Logs

I know I can do this with adb and catlog but how? 

### Additional information

Back to version 18.9.1 everything is stable again.

**Comment by iamrasel** [comment]
I feel nothing like this, maybe I should check the changes between those two versions.

**Comment by iamrasel** [comment]
This may solve... next release.
