### ISSUE TITLE
Built-in option to turn Lunar Launcher into default launcher

### ISSUE THREAD

**Issue by Terkyz** [iamrasel/lunar-launcher#21]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/iamrasel/lunar-launcher/issues) or [closed](https://github.com/iamrasel/lunar-launcher/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have already checked the [WIKI](https://github.com/iamrasel/lunar-launcher/wiki) pages and made sure that the feature isn't already exist.
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.

### Feature description

For some users it may be confusing that installing and running Lunar Launcher simply opens the launcher settings, but not the launcher as such, and you have to manually configure it in the device settings. 

It would be great to have the possibility to automate this with a button, maybe you can add this as an option in the "More" tab.

### Additional information

The update to the quick navigation bar looks beautiful.

**Comment by iamrasel** [comment]
Done, in **Advance** section.

> The update to the quick navigation bar looks beautiful.

Thanks, you can support if you want.
