### ISSUE TITLE
Date format

### ISSUE THREAD

**Issue by neoroot** [iamrasel/lunar-launcher#22]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/iamrasel/lunar-launcher/issues) or [closed](https://github.com/iamrasel/lunar-launcher/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have already checked the [WIKI](https://github.com/iamrasel/lunar-launcher/wiki) pages.
- [X] I have taken the time to fill in all the required details. I understand that the question will be dismissed otherwise.

### What is/are your question(s)?

Where can I get the list for necessary letters to format date?

**Comment by iamrasel** [comment]
Already answered in wiki's [faq](https://github.com/iamrasel/lunar-launcher/wiki/FAQs) page, check again carefully.
