### ISSUE TITLE
Add option to hide Favourite contacts and urls.

### ISSUE THREAD

**Issue by rozari0** [iamrasel/lunar-launcher#27]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/iamrasel/lunar-launcher/issues) or [closed](https://github.com/iamrasel/lunar-launcher/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have already checked the [WIKI](https://github.com/iamrasel/lunar-launcher/wiki) pages and made sure that the feature isn't already exist.
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.

### Feature description

Actually I don't need it and I'd like to hide this.

**Comment by iamrasel** [comment]
Okay.

**Comment by iamrasel** [comment]
Done, settings for this can be found in **More**  section.

**Comment by rozari0** [comment]
> Done, settings for this can be found in **More** section.

Thanks. :p
