### ISSUE TITLE
Widgets on homescreen

### ISSUE THREAD

**Issue by shumafuk** [iamrasel/lunar-launcher#28]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/iamrasel/lunar-launcher/issues) or [closed](https://github.com/iamrasel/lunar-launcher/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have already checked the [WIKI](https://github.com/iamrasel/lunar-launcher/wiki) pages and made sure that the feature isn't already exist.
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.

### Feature description

I understand that launcher want be minimalistic, but ability to add widgets on homescreen (where clock's are) would be useful.

**Comment by iamrasel** [comment]
There's already an issue on asking for widget support - #11. As I told there, widget support will be implemented soon. But it will not be on home screen.

**Comment by Terkyz** [comment]
> There's already an issue on asking for widget support - #11. As I told there, widget support will be implemented soon. But it will not be on home screen.

What if Lunar Launcher had its own widgets? I mean, for example, the box where the RAM of my device appears could be a "widget" of Lunar Launcher, and so maybe other widgets like clocks, ToDo's, timers, etc. could be added.

Although I remember you wanted to remove those boxes from there?

**Comment by iamrasel** [comment]
@Terkyz Yeah, those boxes will be replaced. And Lunar Launcher won't have it's own widgets.

**Comment by ElSebita** [comment]
Lunar looks very interesting but I need my calendar app widget visible on the home screen. 😢

**Comment by iamrasel** [comment]
> Lunar looks very interesting but I need my calendar app widget visible on the home screen. cry

Already [replied](https://github.com/iamrasel/lunar-launcher/issues/28#issuecomment-1297235631).

**Comment by iamrasel** [comment]
✅
