### ISSUE TITLE
Automatically open the App Drawer when in the application menu

### ISSUE THREAD

**Issue by Terkyz** [iamrasel/lunar-launcher#29]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/iamrasel/lunar-launcher/issues) or [closed](https://github.com/iamrasel/lunar-launcher/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have already checked the [WIKI](https://github.com/iamrasel/lunar-launcher/wiki) pages and made sure that the feature isn't already exist.
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.

### Feature description

When I go to the application menu, my keyboard opens automatically.

### Additional information

Although it is obvious, an option to turn this behavior on or off in the Lunar Launcher settings is available.

**Comment by iamrasel** [comment]
I couldn't understand what you said, confusing.🥴 Try to be more clear and specific.

**Comment by rozari0** [comment]
Just select 'Search with keyboard' negative from App Drawer in settings.

**Comment by Terkyz** [comment]
> I couldn't understand what you said, confusing.woozy_face Try to be more clear and specific.

In Olauncher Clutter Free, another great minimalist FOSS launcher for Android that is based on a list of apps and nothing else, I have the option to search in the list of apps the specific app or manually type the name to find it, in this launcher I have the option to make the keyboard of my device to [open automatically when entering the list of apps](https://imgur.com/a/aXcyQIL) and personally I feel this is quite efficient, rather than alphabetically search the app, and since Lunar also has an app search engine using text you could add the ability to have the keyboard open automatically

**Comment by iamrasel** [comment]
As much I could understand, you want that keyboard will popup automatically with the app list. You don't want to tap on the alphabets to open the keyboard, right? @Terkyz

**Comment by Terkyz** [comment]
> As much I could understand, you want that keyboard will popup automatically with the app list. You don't want to tap on the alphabets to open the keyboard, right? @Terkyz

Yep

**Comment by iamrasel** [comment]
> Yep

To me, that thing is annoying. So, now I have no plan to add such thing, and I am closing this issue. But, if more people recommend/ask for this, I may change my mind.
