### ISSUE TITLE
System stats section

### ISSUE THREAD

**Issue by 1BitLog** [iamrasel/lunar-launcher#30]
### Checklist

- [x] I made sure that there are **no existing issues** - [open](https://github.com/iamrasel/lunar-launcher/issues) or [closed](https://github.com/iamrasel/lunar-launcher/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have already checked the [WIKI](https://github.com/iamrasel/lunar-launcher/wiki) pages and made sure that the feature isn't already exist.
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.

### Feature description

Add the option to **hide** or **show** the "system stats section" in the settings menu.

### Additional information

It would also be nice to be able to customize the information displayed in this status menu.

**Comment by iamrasel** [comment]
Okay

**Comment by iamrasel** [comment]
Doing in a different way.
