### ISSUE TITLE
Add option to hide inactive bars. 

### ISSUE THREAD

**Issue by rozari0** [iamrasel/lunar-launcher#31]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/iamrasel/lunar-launcher/issues) or [closed](https://github.com/iamrasel/lunar-launcher/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have already checked the [WIKI](https://github.com/iamrasel/lunar-launcher/wiki) pages and made sure that the feature isn't already exist.
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.

### Feature description

![Screenshot_20221117-034202](https://user-images.githubusercontent.com/61970262/202300888-1a80ac7b-7800-40ef-9f0f-afeba06ff7e1.jpeg)
Like this screenshot, my device doesn't support changing notification and call sound.

I would like to hide those.

**Comment by iamrasel** [comment]
Those sliders have nothing to do with device's support. When the device is in silent/dnd mode, those sliders stay inactive, as android doesn't support changing those volumes then.
