### ISSUE TITLE
[Feature Request] Customized gestures

### ISSUE THREAD

**Issue by Terkyz** [iamrasel/lunar-launcher#37]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/iamrasel/lunar-launcher/issues) or [closed](https://github.com/iamrasel/lunar-launcher/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have already checked the [WIKI](https://github.com/iamrasel/lunar-launcher/wiki) pages and made sure that the feature isn't already exist.
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.

### Feature description

Have a list of gestures already defined (e.g. press home button, double tap the screen, etc) and a list of actions to assign to them (such as open app drawer, launch x app, etc).

### Additional information

If this feature is accepted, I would appreciate if it would be possible to have an action to open the app drawer with the keyboard open as a "default function".

**Comment by The-Repo-Club** [comment]
i like this idea :) i may do a PR for the swipe down so you can chose notification or quick settings as i already know how to do that :)

**Comment by iamrasel** [comment]
@Terkyz Several gestures and for them, a number of actions to choose from, that would be trickier. So for now, I don't want to work on this. May or may not be someday. :pensive:

**Comment by iamrasel** [comment]
> i like this idea :) i may do a PR for the swipe down so you can chose notification or quick settings as i already know how to do that :)

If I get it right, swipe down gesture already opens the notification panel.

**Comment by The-Repo-Club** [comment]
> > i like this idea :) i may do a PR for the swipe down so you can chose notification or quick settings as i already know how to do that :)
> 
> If I get it right, swipe down gesture already opens the notification panel.

Yes it does but it would be cool to have a choice if it can do quick settings :)
