### ISSUE TITLE
[Feature Request] Add warning when removing shortcuts

### ISSUE THREAD

**Issue by The-Repo-Club** [iamrasel/lunar-launcher#39]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/iamrasel/lunar-launcher/issues) or [closed](https://github.com/iamrasel/lunar-launcher/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have already checked the [WIKI](https://github.com/iamrasel/lunar-launcher/wiki) pages and made sure that the feature isn't already exist.
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.

### Feature description

`/* reset the shortcut on long click */`

The function after this should come up and confirm you wanna remove the short cut i have done it by mistake so many times

**Comment by iamrasel** [comment]
Okay, will be done. Thanks for the suggestion.

**Comment by The-Repo-Club** [comment]
cheers
