### ISSUE TITLE
add keyboard when launching apps

### ISSUE THREAD

**Issue by Im-Kal** [iamrasel/lunar-launcher#4]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/iamrasel/lunar-launcher/issues) or [closed](https://github.com/iamrasel/lunar-launcher/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have already checked the [WIKI](https://github.com/iamrasel/lunar-launcher/wiki) pages and made sure that the feature isn't already exist.
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.

### Feature description

I would like a keyboard just how launch works. Navigating using the side letters is pretty hard.

**Comment by iamrasel** [comment]
I have also noticed that feature in **luanch**. But after adding that thing, I don't like the current look of that app. So, still I have no plan to add such feature in **Lunar Launcher**. But if any better ui idea comes up to my mind without losing the current quality, I will surely integrate `search with keyboard` feature.

**Comment by Im-Kal** [comment]
Hmm, maybe enable a setting for enabling either keyboard or letter mode, best of both worlds.

**Comment by Im-Kal** [comment]
Also make it auto-select the keyboard when in keyboard mode. I think adding this will make this the single best launcher.

**Comment by iamrasel** [comment]
Thank you for all these suggestions, i'll keep these in my mind. Keep using and support the development.😊

**Comment by Im-Kal** [comment]
Sure :D, I very much look forward to the update which implements this. Great work mate!

**Comment by iamrasel** [comment]
Done

**Comment by Im-Kal** [comment]
Damn, good job

**Comment by Im-Kal** [comment]
Just downloaded again, how do I enable the keyboard? I enabled it in settings of Lunar but its not showing in app drawer view

**Comment by iamrasel** [comment]
Just click on any search key button like before, and the keyboard will pop up automatically.

**Comment by Im-Kal** [comment]
Bit inconvenient to do so...
