### ISSUE TITLE
Keyboard shows only after a letter is clicked

### ISSUE THREAD

**Issue by Huge** [iamrasel/lunar-launcher#46]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/iamrasel/lunar-launcher/issues) or [closed](https://github.com/iamrasel/lunar-launcher/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.

### App version

2.3

### Android version

9

### Steps to reproduce the bug

1. set the first preference for App drawer to positive

2. Go to app drawer screen, only the list and the alphabet show, no keyboard until I click a letter/character.

### Expected behavior

Show the entry field properly and raise the keyboard for it.
Ideally shrink the list too so that it only uses place above my keyboard.
Perhaps hide the build-in characters on the sides.

### Additional information

Please fix and coffee(×X) is yours!+)

**Comment by iamrasel** [comment]
Already taken care of with this commit - eb2cb325f62292974f07ca208eb7349141efa534. You can check by trying the latest workflow build from the [Actions](https://github.com/iamrasel/lunar-launcher/actions) tab. Or, to get from f-droid, you will have to wait for the next release.

**Comment by Huge** [comment]
I see, these are very promising news for me!
I went with the .apk from the .zip at https://github.com/iamrasel/lunar-launcher/actions/runs/4083667277 but that failed during installation.
![Screenshot_20230207_203852_com google android packageinstaller](https://user-images.githubusercontent.com/111648/217348647-29d648bf-a33f-4560-afa3-cf72d354a345.jpg)

**Comment by iamrasel** [comment]
If f-droid version is already installed, uninstall that one and then retry to install above apk. The apk from f-droid and above apk, both are signed with different signing key. This confliction might not letting you install over previous version.

**Comment by Huge** [comment]
Yeah, that "worked" in the sense the installation finished. I've lost my to-do and settings, which was not much, but the problem is the settings are not accessible there anymore as the app now previews the launcher and doesn't provide "settings app".

**Comment by iamrasel** [comment]
You can access to the launcher settings by long pressing (tap & hold) on the clock-date area (inside battery percentage indicator circle) in home screen.

**Comment by Huge** [comment]
Good, sounds like a _magic method_ (not for the uninitiated;) from the UX perspective though.
[Cheers](https://www.buymeacoffee.com/iamrasel)!

**Comment by iamrasel** [comment]
@folovco It is mentioned in the welcome dialog that appears at the first launch.
