### ISSUE TITLE
support for All miui gestures

### ISSUE THREAD

**Issue by Wjxfi** [iamrasel/lunar-launcher#48]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/iamrasel/lunar-launcher/issues) or [closed](https://github.com/iamrasel/lunar-launcher/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have already checked the [WIKI](https://github.com/iamrasel/lunar-launcher/wiki) pages and made sure that the feature isn't already exist.
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.

### Feature description

it doesn't add up right now.

**Comment by iamrasel** [comment]
Couldn't understand your issue properly.
