### ISSUE TITLE
Add feature of adding feed more than one.

### ISSUE THREAD

**Issue by rozari0** [iamrasel/lunar-launcher#5]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/iamrasel/lunar-launcher/issues) or [closed](https://github.com/iamrasel/lunar-launcher/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have already checked the [WIKI](https://github.com/iamrasel/lunar-launcher/wiki) pages and made sure that the feature isn't already exist.
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.

### Feature description

Right now lunar support only one feed, that would be great if I can get update of more than one feed.

**Comment by iamrasel** [comment]
When I first built this launcher, it had three feeds. But I removed two to acquire space for other features. I also would like to have more than one feed, but it's not just a rss feed reader app. Sorry, I can't add more feed. But I hope future releases will be able to amaze you.

**Comment by rozari0** [comment]
Thanks for letting me know and awesome launcher. :)

**Comment by illiakozey** [comment]
That would be a very nice feature, can't live without that (basically makes the whole RSS feature useless for me). Besides, the best launcher I've ever used, big thanks.

**Comment by 4e576rt8uh9ij9okp** [comment]
I agree, your RSS feed could replace my RSS app that I use.

I could see it being more useful to swipe left and read some news that I'm interested in.

The title of the app says "feature rich with minimal look" so me only being allowed 1 single feed isn't feature rich. I can use a RSS app but then it's not very minimalistic.

I really look forward to have a nicer feed and more than 1

**Comment by calm3285** [comment]
I use miniflux for the feeds, but i cant use it with lunar because i need to authentify

**Comment by calm3285** [comment]
What about a fever api integration?
