### ISSUE TITLE
Left-align-option in app drawer

### ISSUE THREAD

**Issue by Jonta** [iamrasel/lunar-launcher#51]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/iamrasel/lunar-launcher/issues) or [closed](https://github.com/iamrasel/lunar-launcher/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have already checked the [WIKI](https://github.com/iamrasel/lunar-launcher/wiki) pages and made sure that the feature isn't already exist.
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.

### Feature description

- Right now, the eye often has to move left and right, because the X-coordinate of the beginning of app names depends on the app name's length
- It would be more comfortable for me to just scan down in the Y-direction. :)
- Right-alignment is probably also interesting to some, perhaps especially to those using RTL-languages

### Additional information

```
Lunar Launcher v2.3
Android 13
```

Supporting article of <170 words: https://practicaltypography.com/centered-text.html

**Comment by michelevantaggi02** [comment]
i like this, it would be cool to add some setting where you can choose the alignment @iamrasel
