### ISSUE TITLE
App-icon-option in app drawer

### ISSUE THREAD

**Issue by Jonta** [iamrasel/lunar-launcher#52]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/iamrasel/lunar-launcher/issues) or [closed](https://github.com/iamrasel/lunar-launcher/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have already checked the [WIKI](https://github.com/iamrasel/lunar-launcher/wiki) pages and made sure that the feature isn't already exist.
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.

### Feature description

- To identify apps faster
- For some, I'd look for the name, for others, the icon
- I understand this may go against the minimal look Lunar Launcher aspires to
- But I find myself wondering what it would be like to have the icons there
- I'd keep the app-name-rows the same size they are now
- Therefore also small icons
- To the left of the app names:
- [icon] App name
- Perhaps it makes sense to make that an option too:
- To the left of the app name
- To the right of the app name
- Both to the left and to the right. :)

- I considered suggesting monochrome versions of the icons
- But them being small as well, might not make sense
- Might not be useful enough in identifying the apps when the icons are both desaturated and small

### Additional information

```
Lunar Launcher v2.3
Android 13
```

This might tie in with https://github.com/iamrasel/lunar-launcher/issues/49

**Comment by ryanwwest** [comment]
I'd love this. I'm running Lunar Launcher on a large tablet widescreen and it's nice, but I'd like to use icons to take better advantage of the full width.
