### ISSUE TITLE
Unification of version numbers possible?

### ISSUE THREAD

**Issue by Jonta** [iamrasel/lunar-launcher#54]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/iamrasel/lunar-launcher/issues) or [closed](https://github.com/iamrasel/lunar-launcher/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have already checked the [WIKI](https://github.com/iamrasel/lunar-launcher/wiki) pages.
- [X] I have taken the time to fill in all the required details. I understand that the question will be dismissed otherwise.

### Question

- [Readme currently says](https://github.com/iamrasel/lunar-launcher/commit/a985128e5ab16eac84ae66caf8d3a998a94c5edb) "As per version 14"
- This confused me, as my version of the app says "2.3"
- I thought I must be far behind the newest version
- It appears that the GitHub-version (?) was used: https://github.com/iamrasel/lunar-launcher/releases
- Which just uses integers

Is it possible to use the same version number in both the app and the releases? :)

**Comment by iamrasel** [comment]
Here, the whole numbers are the version code/build number. And, the decimal numbers are the version name. I hope you get the difference.
https://github.com/iamrasel/lunar-launcher/blob/396f7c0fc0bcad89fae795d78b600118147adc69/app/build.gradle.kts#L15-L16
