### ISSUE TITLE
Can't add quick access apps

### ISSUE THREAD

**Issue by Jonta** [iamrasel/lunar-launcher#55]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/iamrasel/lunar-launcher/issues) or [closed](https://github.com/iamrasel/lunar-launcher/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.

### App version

2.3

### Android version

Android 13 (Graphene OS)

### Steps to reproduce the bug

- Commit dba61f89ca8cd2a0fad0ba4b35a317e54d067442 added `fastlane/metadata/android/en-US/images/phoneScreenshots/4.png` - https://github.com/iamrasel/lunar-launcher/raw/main/fastlane/metadata/android/en-US/images/phoneScreenshots/4.png
- Mine seems unable to add quick access buttons for apps, as shown in that screenshot
- Instead:

![lunar-launcher-tray](https://user-images.githubusercontent.com/359397/225942209-762056b9-bc71-433c-a628-ba4901a0b5a6.png)

**Comment by iamrasel** [comment]
To add an app in quick access panel follow these steps:
1. Tap and hold that app from the apps list.
2. You'll see like below. From there (marked box), tap on a position to select for the app.
3. That's it, the app is added. Go, check and add more (up to 6).

![qa](https://user-images.githubusercontent.com/77199897/235345815-baf39627-a1c4-4b5e-b8b5-699b42941a39.jpg)
