### ISSUE TITLE
URL-buttons not correctly aligned

### ISSUE THREAD

**Issue by Jonta** [iamrasel/lunar-launcher#56]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/iamrasel/lunar-launcher/issues) or [closed](https://github.com/iamrasel/lunar-launcher/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.

### App version

2.3

### Android version

Android 13 (Graphene OS)

### Steps to reproduce the bug

- Main screen
- Pull up, to get menu shown in screenshot below
- Plus-symbols and button with letter D are misaligned, compared to https://github.com/iamrasel/lunar-launcher/commit/dba61f89ca8cd2a0fad0ba4b35a317e54d067442 - `fastlane/metadata/android/en-US/images/phoneScreenshots/4.png` - https://github.com/iamrasel/lunar-launcher/raw/main/fastlane/metadata/android/en-US/images/phoneScreenshots/4.png

![lunar-launcher-tray](https://user-images.githubusercontent.com/359397/225944827-a00cfc2d-9ed3-49a2-8059-b69eae670c70.png)

### Additional information

- Pixel 6a
- https://www.gsmarena.com/google_pixel_6a-11229.php
- Size: 6.1 inches, 90.7 cm2 (~83.0% screen-to-body ratio)
- Resolution: 1080 x 2400 pixels, 20:9 ratio (~429 ppi density)

**Comment by iamrasel** [comment]
#63
