### ISSUE TITLE
String "Contacts"(?) truncated beyond recognition when trying to shortcut

### ISSUE THREAD

**Issue by Jonta** [iamrasel/lunar-launcher#58]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/iamrasel/lunar-launcher/issues) or [closed](https://github.com/iamrasel/lunar-launcher/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.

### App version

2.3

### Android version

Android 13 (Graphene OS)

### Steps to reproduce the bug

- Main screen
- Pull up, to get menu shown in screenshot below
- Tap a plus-symbol

### Actual behavior

Button says "Cont…"

### Expected behavior

Button says "Contacts"

### Screenshots/Screen recordings

![lunar-launcher-add](https://user-images.githubusercontent.com/359397/225963240-bc695f7a-de08-4a66-8e03-99095b50db9a.png)

### Additional information

- Before investigating, I thought "Cont…" had truncated "Contents"
- This seems to be in `app/src/main/res/layout/shortcut_maker.xml`
- -
- Pixel 6a
- https://www.gsmarena.com/google_pixel_6a-11229.php
- Size: 6.1 inches, 90.7 cm2 (~83.0% screen-to-body ratio)
- Resolution: 1080 x 2400 pixels, 20:9 ratio (~429 ppi density)
- -
- Font size: 2/4
- Dispaly size: 3/5

**Comment by michelevantaggi02** [comment]
It would be nice to replace text with icons in this case

**Comment by iamrasel** [comment]
Thanks for the suggestion @michelevantaggi02
