### ISSUE TITLE
Ability to hide apps from the app list

### ISSUE THREAD

**Issue by Terkyz** [iamrasel/lunar-launcher#6]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/iamrasel/lunar-launcher/issues) or [closed](https://github.com/iamrasel/lunar-launcher/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have already checked the [WIKI](https://github.com/iamrasel/lunar-launcher/wiki) pages and made sure that the feature isn't already exist.
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.

### Feature description

A simple ability that I long press on the name of the app I want to hide and it hides it from my list of apps

### Additional information

Of course, an option in the Lunar Launcher settings to unhide said app

**Comment by iamrasel** [comment]
Features like app hide, lock, rename and many more will be added soon in the future releases. You all just have to wait and keep supporting.😉
