### ISSUE TITLE
Screen rotates with rotation active and crashes the app

### ISSUE THREAD

**Issue by michelevantaggi02** [iamrasel/lunar-launcher#60]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/iamrasel/lunar-launcher/issues) or [closed](https://github.com/iamrasel/lunar-launcher/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.

### App version

2.4

### Android version

Android 11 - MIUI 12.5.1

### Steps to reproduce the bug

1. Activate screen rotation
2. Rotate horizontally
3. Try a couple of times (it doesn't happen at first try)

### Expected behavior

Screen should remain vertical, or it shouldn't crash the home screen

### Screenshots/Screen recordings

![Screenshot_2023-04-27-09-24-55-006_rasel lunar launcher](https://user-images.githubusercontent.com/56927140/234790255-7958c944-411a-4283-8025-415550794d17.jpg)

**Comment by iamrasel** [comment]
It doesn't crash for me, i've tried changing the orientation several times. Forcing the view to portrait, wouldn't that be inconvenient for some users?

**Comment by michelevantaggi02** [comment]
@iamrasel I don't know why but on the emulator worked fine without crashes, maybe is a problem of miui

**Comment by michelevantaggi02** [comment]
I don't think it could be an inconvenient, when is horizontal it cuts out most of the interface

**Comment by iamrasel** [comment]
If it doesn't crash, then letting the user decide their preferred orientation would be helpful. On tablet devices it works fine with landscape mode, the interface don't get cut.

So, I hope it's okay to close this issue and the related PR.
