### ISSUE TITLE
System stats progressBars blinking on update

### ISSUE THREAD

**Issue by michelevantaggi02** [iamrasel/lunar-launcher#64]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/iamrasel/lunar-launcher/issues) or [closed](https://github.com/iamrasel/lunar-launcher/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.

### App version

2.4

### Android version

Android 13

### Steps to reproduce the bug

1. Just open the system info drawer

### Expected behavior

When the coroutine updates the ram and cpu bars it deletes everything and creates again a view making it blink on and off every second

**Comment by iamrasel** [comment]
Those views are supposed to update in every second.

**Comment by michelevantaggi02** [comment]
> Those views are supposed to update in every second.

https://user-images.githubusercontent.com/56927140/236119210-16094ed7-eb2a-4f5f-bc86-269089595d03.mp4

Yes but this happens when you delete everything and recreate it again, it's not necessary to do it you can just edit the value of a fixed progressBar
