### ISSUE TITLE
Value for battery, battery voltage and temperature are mixed up

### ISSUE THREAD

**Issue by gingercookies** [iamrasel/lunar-launcher#66]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/iamrasel/lunar-launcher/issues) or [closed](https://github.com/iamrasel/lunar-launcher/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.

### App version

2.4 (Downloaded from F-Droid)

### Android version

Android 12 SKQ1.211103.001 with Miui 13.0.8.0

### Steps to reproduce the bug

1. From home swipe left to go to System stats
2. Scroll down to the bottom
3. See the value is mixed up 

### Expected behavior

The value for the battery, battery voltage and temperature are displayed correctly

### Screenshots/Screen recordings

![Screenshot_2023-04-28-09-43-47-272_rasel lunar launcher](https://user-images.githubusercontent.com/77981365/235045798-9963964e-97a7-47df-bc4d-fbcd89fa02a1.png)

**Comment by michelevantaggi02** [comment]
It's not 3 values, it's 2.
The system splits "Battery Temperature" on 2 lines breaking the alignment
