### ISSUE TITLE
QuickSwitch support

### ISSUE THREAD

**Issue by dotmashrc** [iamrasel/lunar-launcher#72]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/iamrasel/lunar-launcher/issues) or [closed](https://github.com/iamrasel/lunar-launcher/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have already checked the [WIKI](https://github.com/iamrasel/lunar-launcher/wiki) pages and made sure that the feature isn't already exist.
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.

### Feature description

Are there any plans to add QuickSwitch support? QuickSwitch lets you change the Recents provider. While it is a feature only available on rooted phones, it would probably be a good feature to add as there are very few launchers that support QuickSwitch.

I love this app due to it's minimalistic look but having a recents provider different from the home screen is a big pet peeve of mine and hence why I have used Lawnchair for years now.

### Additional information

[More information on QuickSwitch](https://forum.xda-developers.com/t/module-3-3-1-quickswitch-quickstep-enabler-for-supported-launchers.3884797/)

**Comment by iamrasel** [comment]
Is there any official documentation on the process of adding it?
