### ISSUE TITLE
Weblate integration

### ISSUE THREAD

**Issue by comradekingu** [iamrasel/lunar-launcher#74]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/iamrasel/lunar-launcher/issues) or [closed](https://github.com/iamrasel/lunar-launcher/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.

### App version

All

### Steps to reproduce the bug

I can get the Weblate integration up and working if you add "kingu" in
https://hosted.weblate.org/access/lunar-launcher/#users

### Expected behavior

Expected the translation to be open, and not locked.

### Additional information

Will also change the translation license to match the repo.

**Comment by iamrasel** [comment]
Addition done. It would be so kind of you, I was having difficulties setting up the project on Weblate for being new there.
