### ISSUE TITLE
"CPU & Battery" tile - Fahrenheit option

### ISSUE THREAD

**Issue by ItamiWasTaken** [iamrasel/lunar-launcher#8]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/iamrasel/lunar-launcher/issues) or [closed](https://github.com/iamrasel/lunar-launcher/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have already checked the [WIKI](https://github.com/iamrasel/lunar-launcher/wiki) pages and made sure that the feature isn't already exist.
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.

### Feature description

I propose to have the temperature (1) be based on what the user inputs in the settings (2).

### Additional information

(1)
![Screenshot_20220920-003001~2](https://user-images.githubusercontent.com/99271684/191168551-71a61965-b8aa-4566-a5bc-6cdf7234bdc0.png)

(2)
![Screenshot_20220920-003433~2](https://user-images.githubusercontent.com/99271684/191168566-841e217b-bf5e-4f94-900e-6e37fd0c6c87.png)

**Comment by iamrasel** [comment]
I could do that. But this system info section is temporary, they will be replaced with something more interesting. So I don't want to waste any time on them.

I just added them to fill up the space to quickly release the app.

**Comment by ItamiWasTaken** [comment]
ahh, I see. I understand

**Comment by iamrasel** [comment]
Done ✅
