### ISSUE TITLE
oled true black for launcher theme

### ISSUE THREAD

**Issue by rosxz** [iamrasel/lunar-launcher#80]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/iamrasel/lunar-launcher/issues) or [closed](https://github.com/iamrasel/lunar-launcher/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have already checked the [WIKI](https://github.com/iamrasel/lunar-launcher/wiki) pages and made sure that the feature isn't already exist.
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.

### Feature description

Add option to select OLED true black as launcher theme, currently the Dark theme option doesn't work as that.
Alternatively, allow for an option to display wallpaper on the launcher, which I think would allow for similar results, although the first option would be better imo.

### Additional information

Lunar Launcher v2.7.1
Android 13

**Comment by creaaidev** [comment]
> Pure black theme for whole application is a good suggestion. Still you can achieve the almost same by selecting the black color (`#ff000000`) as your background from `Appearances`.
> 
> And, displaying wallpaper as launcher background has already been included. You just need to select the transparent color (`#00000000`) as your background from `Appearances`.

Oh, I totally missed that. I was clicking in Change Wallpaper and not in the color icon, it does seem to work, thanks a ton!
