### ISSUE TITLE
Tiles - add customisability

### ISSUE THREAD

**Issue by ItamiWasTaken** [iamrasel/lunar-launcher#9]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/iamrasel/lunar-launcher/issues) or [closed](https://github.com/iamrasel/lunar-launcher/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have already checked the [WIKI](https://github.com/iamrasel/lunar-launcher/wiki) pages and made sure that the feature isn't already exist.
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.

### Feature description

the tiles screen should be customizable in my honest opinion. I do understand that this is vague, so I feel the ability to toggle tiles would allow further development in the future.

### Additional information

one could toggle off the sdcard tile and replace it with, say a flashlight or notification tile

**Comment by iamrasel** [comment]
Your suggestion was good, but as I [answered](https://github.com/iamrasel/lunar-launcher/issues/8#issuecomment-1252307130) to your earlier issue, I won't work on those thing anymore. I hope you understood.
