### ISSUE TITLE
swipe up gesture detection very low for Sony Xperia 10

### ISSUE THREAD

**Issue by neith00** [iamrasel/lunar-launcher#90]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/iamrasel/lunar-launcher/issues) or [closed](https://github.com/iamrasel/lunar-launcher/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.

### App version

2.7.2(34)

### Android version

Android 13

### Steps to reproduce the bug

While on the home screen I swipe up with one finger from bottom to middle of the screen. Most if the time the gesture is recognize as as left or right swipe. It's sad cause shortcuts are hard to reach. Otherwise left and right gestures are working perfectly.
As there are no settings for gesture I guess something is different on my Sony's phone because otherwise everyone would have the same issue.

### Expected behavior

Swipe up with one finger and opens the shortcuts

### Screenshots/Screen recordings

None

### Logs

None

### Additional information

None

**Comment by iamrasel** [comment]
It's a bit hard on every phone. I've tried to solve this, but failed to improve any.

**Comment by salihburock** [comment]
> It's a bit hard on every phone. I've tried to solve this, but failed to improve any.

Could changing the gesture help that? For example double tapping the home would trigger that menu to show

**Comment by neith00** [comment]
Yeah it's a good idea!

Jean-Alexis

------- Original Message -------

**Comment by iamrasel** [comment]
> Could changing the gesture help that? For example double tapping the home would trigger that menu to show

The double tapping gesture is already assigned for screen lock.:confused:

**Comment by umutucak** [comment]
Could we add an option to choose either;

- lock
- shortcut menu

with the double click?

I would be willing to work on an implementation if you think it is an appropriate feature.

**Comment by umutucak** [comment]
or perhaps update the `onFling()` as per [this implementation](https://stackoverflow.com/a/26387629)? i believe a reason for the sensitivity is because the `diffX > diffY` in `SwipeTouchListener` is giving priority to horizontal swipes.

**Comment by salihburock** [comment]
I agree. Something must have be off with that. It was hard for me to get used to that sensitivity. I used to accidentally open app list instead of app drawer

**Comment by iamrasel** [comment]
@umutucak I like the second idea, might implement this. :+1:
> Replace the `Negative` choice with `Shortcut Menu Access`. Rename `Double Tap Lock Method` to `Double Tap Feature`.
