### ISSUE TITLE
Hyphen (-) unsupported in app search

### ISSUE THREAD

**Issue by Lachlainn** [iamrasel/lunar-launcher#91]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/iamrasel/lunar-launcher/issues) or [closed](https://github.com/iamrasel/lunar-launcher/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.

### App version

2.7.2 (34)

### Android version

Andoird 12

### Steps to reproduce the bug

1. go to app list
2. search for an app with a hypen in the name (i was looking for f-droid
3. "0 results"

### Expected behavior

To open or show the app. It does find it if i write "fdroid" without the hypen.

### Screenshots/Screen recordings

![Screenshot_20230917-115829](https://github.com/iamrasel/lunar-launcher/assets/4345937/2405a67e-2d93-4706-8171-6394c55879c5)

### Additional information

Easily worked around by user.

**Comment by iamrasel** [comment]
I had removed all kind of symbol support from the search box a long time ago after some users suggested that they are annoying. So, it won't be re-added.
