### ISSUE TITLE
App Search does not clear after an app launches if more keys pressed then needed characters to match the app

### ISSUE THREAD

**Issue by salihburock** [iamrasel/lunar-launcher#92]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/iamrasel/lunar-launcher/issues) or [closed](https://github.com/iamrasel/lunar-launcher/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [x] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.

### App version

2.8

### Android version

Android 13

### Steps to reproduce the bug

1. Enable Quick Launch
2. Type a string that has more characters than needed information to match the apps name eg: Typing "Cloc" where there is only one matching app for "Clo" leaves the last "c" at the search bar

### Additional information

I can fix that by not typing more than requiered characters but sometimes I am unsure that it will be enough so I type till the app opens and the time it finds the app and starts to run it is long enoguh to type more of the apps name after that when I want to launch a new app I have to delete the remains

**Comment by iamrasel** [comment]
Weird issue, i've faced no such thing so far. Could you please share a screen record so that I can understand the problem clearly?

**Comment by salihburock** [comment]
https://github.com/iamrasel/lunar-launcher/assets/94194901/261174e8-e506-4848-8984-1a841ed22e5c

"cl" had only one match and that was "Clock". Something happened to "o" in the middle and last "ck" remained there.

**Comment by iamrasel** [comment]
Tried playing your video through different browsers and devices, but it's not loading at all.

However, when `Quick Launch` is turned on, `Clock` should be launched as soon as you finish typing `cl` (if that's the only match). How are you able to type the later alphabets?

**Comment by salihburock** [comment]
There is a latency between when I type "cl" and until the app launches if its not the case with the launcher I am assuming something else might be wrong with my phone then

**Comment by iamrasel** [comment]
The `quick launch` feature is - as soon as the search result reaches only one item, quickly open it. If that's not working properly, then _something might be wrong_ on your end. Could you please check this on another device to see if the issue also persists there?

**Comment by salihburock** [comment]
Tried it on my friends device and it erased the input box after closing the app if the always go home is positive. But if it is negative launcher starts from the app list and letters letters I type remain there due to the latency between inputs and the process. So I it depends on the Always Go Back To Home option.

**Comment by iamrasel** [comment]
The search input box should clear itself and disappear as soon as you leave the app drawer screen, it has already been coded to act that way.
https://github.com/iamrasel/lunar-launcher/blob/da5e0c500ca134fcf73cf5803f5104cd3573fc96/app/src/main/kotlin/rasel/lunar/launcher/apps/AppDrawer.kt#L169-L172
https://github.com/iamrasel/lunar-launcher/blob/da5e0c500ca134fcf73cf5803f5104cd3573fc96/app/src/main/kotlin/rasel/lunar/launcher/apps/AppDrawer.kt#L276-L288

**Comment by salihburock** [comment]
Tried on 4 devices and an emulator. While it runs perfectly on the emulator, all the devices showed the same error. Tried adding additional code to force clear the App Search but it didn't make any difference.

**Comment by salihburock** [comment]
I wanted to dive into this but I am gonna close this for now. If I find something I will inform you thanks for everything!

**Comment by iamrasel** [comment]
You can reopen the issue any time you want.😉
