### ISSUE TITLE
[Feat. Req.] Customize accent color? 

### ISSUE THREAD

**Issue by momoe** [iamrasel/lunar-launcher#94]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/iamrasel/lunar-launcher/issues) or [closed](https://github.com/iamrasel/lunar-launcher/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have already checked the [WIKI](https://github.com/iamrasel/lunar-launcher/wiki) pages and made sure that the feature isn't already exist.
- [X] I have taken the time to fill in all the required details. I understand that the feature request will be dismissed otherwise.
- [X] This issue contains only one feature request.

### Feature description

By default Lunar launcher uses a lavender color for it's highlighted accents on it's widgets and whatnot. Please allow a custom color preference to better match our personal theme choices.

### Additional information

The ability for it to sample the current wallpaper and whip out a simple color pallet to choose wouldn't go amiss.

**Comment by iamrasel** [comment]
[Dynamic color](https://developer.android.com/develop/ui/views/theming/dynamic-colors) feature has already been included. So, if you are facing only a `lavender` (🟣) like color, that means your device is running with android <12.

> Dynamic Color, which was added in Android 12, enables users to personalize their devices to align tonally with the color scheme of their personal wallpaper or through a selected color in the wallpaper picker.

And, it is still not possible to let the users change the accent color by their choice. Only thing I could do is, create a bunch of themes with different accent colors, and then let you (users) choose from them. But this would need much time, and still users might end up disliking those colors.

So, i'm sorry to say that, this enhacement might not be worked on by me... ever.
